### ISSUE TITLE
Requested Design Review

### ISSUE THREAD

**Issue by jkulton** [DarkArc/haxing.ninja#1]
I figured this was one of the better ways to aggregate feedback. GitHub allows pasting of screenshots, formatting with Markdown, etc.

## Initial Thoughts

Your overall design is clear, and has a 'content-first' feel to it. I like that.

* [x] Clearly explains what it is you do
* [x] Makes what you've done easily read and/or accessed
* [x] Not too many main nav links (3-5 is the sweet spot for personal sites imo)

### Homepage/blog entries

I'd make the titles of your blog entries a link to the entry, right now they are normal text elements.  It was the first thing I tried clicking when I visited the homepage, it's a common enough behavior on many blogs that I think other users will try it too.

<img width="537" alt="Screen Shot 2019-03-14 at 8 16 09 PM" src="https://user-images.githubusercontent.com/6694167/54400019-7c3eb080-4697-11e9-8155-e0e8769b5e0f.png">

This might be a little _too_ nit-picky, but I'd find a way to left align the `Read More` links with the blurb of the article.

<img width="160" alt="Screen Shot 2019-03-14 at 8 51 35 PM" src="https://user-images.githubusercontent.com/6694167/54400808-105e4700-469b-11e9-8bfc-7b9645043bd8.png">

I've seen designers go both ways on padding like this, but I like aligning things to the left.

### Individual blog entry

While it isn't 💯% necessary, it might be worth looking into using the `<article>`[(mdn docs)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) element on this page, if even just for the semantic meaning the tag brings with it.

### Gallery

Might add a bit of personality to put an `<h1>` or `<h2>` header on the gallery page along with a little paragraph blurb explaining the context.

e.g.

```html
<h1>Gallery</h1>

<p>Photos taken while traveling, exploring, or just living everyday life.</p> 
<!-- please don't use this actual wording lol -->
```

### About Me

Noticed a few instances of awkward wording, I've added bold italics to the below quotes to indicate the changes I suggest.

> I’ve both created, and contributed to, _**a**_  number of open source projects over the years, primarily in Java, JavaScript, and C++.

> Most recently, I created _**Packet**_ Loss Gaming with the intention to create and promote, a friendly environment of respectful gamers.

> I started using Linux as my primary operating system _**in**_ early 2013.

I'd prefer your profile to be at the top of About Me on mobile. Ex:

<img width="429" alt="Screen Shot 2019-03-14 at 8 58 18 PM" src="https://user-images.githubusercontent.com/6694167/54400995-fc671500-469b-11e9-8251-5f9891aa85fa.png">

### 404

lol I like your 404 page

> Oh no :(

## Summary

Although I had some suggestions here and there, I think this is a very solid personal site. Good work! 👍 🎉

**Comment by DarkArc** [comment]
Implemented several of your suggestions; Thanks Jon :)

Left align read me links: https://github.com/DarkArc/haxing.ninja/commit/0678e233b89deaee6869f6b7af56b1412f466ec7
Improve about page layout on small screens: https://github.com/DarkArc/haxing.ninja/commit/aab9decf80925998e66a771b0c13d0867605b740
Fixed typos: https://github.com/DarkArc/haxing.ninja/commit/ea4bbda209817f365d80e208de1026d20dae3ba6

> I'd make the titles of your blog entries a link to the entry, right now they are normal text elements.

Looking at it, I think I like the "Read more" link better, making the headers links just puts way too much blue on the page. :sweat_smile: I think it's probably fine because, they're excerpts.

> While it isn't 100% necessary, it might be worth looking into using the <article>(mdn docs) element on this page, if even just for the semantic meaning the tag brings with it.

I'll probably do this eventually, not sure it makes much of a difference though? Maybe SEO?

> Gallery

The gallery needs a _lot_ of work, I'll be doing other things to it in the future hopefully; this is just v1 of it.
